version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - curl -sSL https://install.python-poetry.org | python3 - --version 1.8.4
      - $HOME/.local/bin/poetry config virtualenvs.create false
    pre_install:
      - $HOME/.local/bin/poetry export --only=docs -o requirements.txt

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/source/conf.py
